### ISSUE TITLE
Hello world or cuc ?

### ISSUE THREAD

**Issue by JamesHyot** [jean-ben-guigui/fal#1]
There's a comment inside App.java that says "Hello world !" but the program prints "Hello cuc !" 
Who should I believe ?

Yours trully

**Comment by jean-ben-guigui** [comment]
In my opinion and with all due respect, you should believe what's printed.
The cuc never lies.

Sincerely yours,

Arthur Duver - étudiant à TSE - AETSE

**Comment by jean-ben-guigui** [comment]
don't close me like this bro 👎

**Comment by JamesHyot** [comment]
Sorry I've been overcuced by this issue
